### ISSUE TITLE
sup-topbar.min.js isn't the same as scroll-up-bar.min.js

### ISSUE THREAD

**Issue by joopvos** [pixelspring/SlideUpTopBar-for-Foundation#1]
![slideuptopbar-for-foundation 2015-03-13 20-29-08](https://cloud.githubusercontent.com/assets/3525026/6645787/a7767872-c9bf-11e4-8094-bfdcd23838b5.png)

**Comment by pixelspring** [comment]
Thanks for spotting that - fixed :)
