### ISSUE TITLE
Alternative style for the scroll up nav?

### ISSUE THREAD

**Issue by nitrokevin** [pixelspring/SlideUpTopBar-for-Foundation#2]
Hi just wondered if its possible to have a different style nav when you scroll back up.

For instance to have a solid background nav when its at the top of the screen and a semi transparent one when you are away from the top?

**Comment by pixelspring** [comment]
Hey @nitrokevin,

This is off the top of my head and untested but you could do something like this:

- Add a new class to your CSS:
`.slideUpTransparent {
  opacity: 0.5;
}`

- Then add a check in the `hasScrolled()` function to see if the content is at the top of the page:
```
if($(window).scrollTop() === 0){
    $('.slideUp').removeClass("slideUpTransparent");
} else {
    $('.slideUp').addClass("slideUpTransparent");
}
```

You might want to get a bit more fancy with the CSS but something along those lines should do it :)

**Comment by nitrokevin** [comment]
Yes this works perfectly, thank you for your help
