### ISSUE TITLE
stops working when foundation is built

### ISSUE THREAD

**Issue by nitrokevin** [pixelspring/SlideUpTopBar-for-Foundation#3]
Hi, I've had this working while the site was in development but as soon as I made a production build it stopped working fully, I made the change you had suggested for the previous issue "Alternative style for the scroll up nav?"

The alternative style is still kicking in correctly but the nav is not moving off screen any more.

I'm using the latest version of foundation through foundationpress, and I wonder if all the new webpack  stuff is having an effect on the script rather than an error with the script itself

**Comment by pixelspring** [comment]
Just had a look at the FoundationPress demo and it appears that webpack (Babel) is forcing strict mode on the minified script and as SlideUpTopBar currently uses `this` in the hasScrolled function, it's not compatible with strict mode. 

I'll push a fix for it :)

**Comment by pixelspring** [comment]
Fixed in master branch :)

**Comment by nitrokevin** [comment]
Thank you so much for that, I was having a panic! :)
